 
morecrops.crops = {
	{type="annual", name="artichoke", description="Artichoke", stages=4, rate=7 },
	{type="annual", name="beat", description="Red Beet", stages=4, rate=7 },
	{type="annual", name="broccoli", description="Broccoli", stages=4, rate=7 },
	{type="annual", name="brusselssprout", description="Brussels Sprout", stages=4, rate=7 },
	{type="annual", name="cabbage", description="Cabbage", stages=4, rate=7 },
	{type="annual", name="cassava", description="Cassava (Tapioca)", stages=4, rate=7 },
	{type="annual", name="chickpea", description="Chickpea", stages=4, rate=7 },
	{type="annual", name="celery", description="Celery", stages=4, rate=7 },
	{type="annual", name="daikon", description="Daikon", stages=4, rate=7 },
	{type="annual", name="garlic", description="Garlic", stages=4, rate=7 },
	{type="annual", name="greenbean", description="Green Bean", stages=4, rate=7 },
	{type="annual", name="leek", description="Leek", stages=4, rate=7 },
	{type="annual", name="lemongrass", description="Lemongrass", stages=4, rate=7 },
	{type="annual", name="onion", description="Onion", stages=4, rate=7 },
	{type="annual", name="peanut", description="Peanut", stages=4, rate=7 }, --[[120 to 150 days]]
	{type="annual", name="radish", description="Radish", stages=4, rate=7 },
	{type="annual", name="soy", description="Soy Bean", stages=4, rate=7 --[[68-86F 80–120 days]] },
	{type="annual", name="spinach", description="Spinach", stages=4, rate=7 },
	{type="annual", name="sugarbeet", description="Sugar Beet", stages=4, rate=7 },
	{type="annual", name="sweetpea", description="Sweet Pea", stages=4, rate=7 },
	{type="annual", name="sweetpotato", description="Sweet Potato", stages=4, rate=7 },
	{type="annual", name="tobacco", description="Tobacco", stages=4, rate=7 },
	{type="annual", name="turnip", description="Turnip", stages=4, rate=7 },

	{type="grain", name="barley", description="Barley", stages=4, rate=7 },
	{type="grain", name="buckwheat", description="Buckwheat", stages=4, rate=7 },
	{type="grain", name="corn", description="Corn", stages=4, rate=7 },
	{type="grain", name="oats", description="Oats", stages=4, rate=7 },
	{type="grain", name="rape", description="Rapeseed", stages=4, rate=7 },
	{type="grain", name="rice", description="Rice", stages=4, rate=7 },
	{type="grain", name="rye", description="Rye", stages=4, rate=7 },
	{type="grain", name="sorghum", description="Sorghum", stages=4, rate=7 },
	{type="grain", name="flax", description="Flax", stages=4, rate=7 },

	{type="perrenial", name="bellpepper", description="Bell Pepper", seasons={2,4},--[[ all climates ]]},
	{type="perrenial", name="chili", description="Chili Pepper", seasons={2,4},--[[ all climates ]]},
	{type="perrenial", name="ghostchili", description="Ghost Chili", seasons={2,4},--[[ all climates ]]},
	{type="perrenial", name="pineapple", description="Pineapple", seasons={2,4},--[[ all climates ]]},
	{type="perrenial", name="cranberry", description="Cranberry", seasons={infinite},--[[ all climates ]]},
	{type="perrenial", name="nettle", description="Stinging Nettle", seasons={infinite},--[[ all climates ]]},

		
}